### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by streaps** [cmeng-git/atalk-android#11]
I'll start to translate strings.xml to German, if nobody else is already working on it.

**Comment by cmeng-git** [comment]
Many thanks for your offer. Some user is already offer help on my request,  to perform the German translation. Just give him few days, will certainly come back to you if he has difficulty to do the translation.

Thank again for your kind offer.

**Comment by cmeng-git** [comment]
UI added in 1.3.2 and others i.e. Bahasa Indonesia and Russian

**Comment by streaps** [comment]
Thanks for the translation. Two things:

I would prefer informal language ("Du" instead of "Sie") in a messaging app. Nowadays it's more common to use informal language.

The layout of the login popup doesn't look good on my 1280x720 screen.

![screenshot_atalk_login_german](https://user-images.githubusercontent.com/15691/41028593-0e914ea8-697a-11e8-8ad7-a75df5d97fa9.png)

**Comment by cmeng-git** [comment]
Thanks for the feedback, would you be able to help to proof read and make correction in the German translation file. The file is in the source directory ./aTalk/src/main/res/values-de/strings.xml. You can return to me for inclusion in the next release. 

As for the layout, I have to keep the menu height to avoid unnecessary scrolling, otherwise I will receive other comments from user with bad UI and login timeout due to scrolling. The layout is actually optimized for English text and with 1080*1920 resolution. One thing you can help is to abbreviate the text so it fit into the space e.g. IBR if this is acceptable to all. The text length optimization may also be needed for other menu items, and certainly I need your help. I know nothing about German language.

For the login UI. you can rotate the phone to landscape mode, I believe the text should fit. However you may be bother by the scrolling to see all text. This is the thing I am trying to avoid when designing this UI.

**Comment by cmeng-git** [comment]
Will you be able to download the German strings.xml and modify. You can send the updated file to me once you have done.
