### ISSUE TITLE
Fail to join foreign room

### ISSUE THREAD

**Issue by narcisgarcia** [cmeng-git/atalk-android#120]
Severe problems to join existing groups not offered by same user's server.

-> Join chat room
Account: myuser@domain1.net
Nick Name: John Doe
Subject: 
Chat Room: popcorn@rooms.domain2.com
-> Press on Join button

Error:
Failed to create chat room for:
Jabber:myuser@domain1.net

**Comment by cmeng-git** [comment]
It is necessary that domain2.com must be configured its service to allow an external user to create chat room, otherwise the room creation from outside user will always fail. Please ensure that you have the permission to create room on domain2.com.

If you are seeing this problem, even you have the permission to create the room, please forward me the debug log to understand the root cause.

**Comment by narcisgarcia** [comment]
domain2 allows external participation (tested also with this room). This room only requires password or invitation to join.
I'm not trying to create but to join.

A friend succeed someway to join that group in same conditions but was using aTalk 2.1.2
Once has updated to 2.2.0 (using F-Droid) my friend tried to clean group subscription and enter again: Impossible now.

**Comment by cmeng-git** [comment]
Yes, there was a change in aTalk v2.2.0; where aTalk will attempt to change the room properties so that the  room created/joined can always support OMEMO chat. Prior to v2.2.0, the room created in the main menu cannot support OMEMO chat. However change of room properties are only owner privilege.

Need to fix this problem for next release.

**Comment by narcisgarcia** [comment]
Joining to a room should not make any automatic properties change to it. When chatroom already exists, it has been created and customized as users (or creators) already wanted.

**Comment by narcisgarcia** [comment]
Due to current month crisis, some users are in a hurry to find open source and neutral solutions to their communications. Issues I've filed these days are related to this circumstance.

Thank you for your comprehension.

**Comment by cmeng-git** [comment]
In aTalk current implementation, it checks the existence of the chat room using only its own server room list. As the room is an external, it cannot find the room and hence proceed to create and update the room properties. This is where the problem started.

**Comment by cmeng-git** [comment]
Please verify the latest aTalk release v2.2.2 has indeed fixed your problem.
