### ISSUE TITLE
Not receiving room invitation

### ISSUE THREAD

**Issue by narcisgarcia** [cmeng-git/atalk-android#121]
Someone from a different server/domain sends me an invitation to a chat room.
Using aTalk 2.2.0 I don't receive any notification or query to accept.

**Comment by cmeng-git** [comment]
To allow users of two different server/domain to chat with each other or to receive invitation, both the users' domains i.e. @domain1.net and @domain2.com must be FQDN and resolved to an ip address accessible from outside.

Please may perform ping to both the domains, and see that both are accessible.
Please send the debug if otherwise.

Currently I am not sure if the service can configured to disallow other outsiders to join group chat.

**Comment by narcisgarcia** [comment]
User1's account domain is public FQDN and points to IP
User2's account domain is public FQDN and points to IP
Room domain is public FQDN and points to CNAME -> public FQDN -> IP

All IPs respond to ping.

How/where can I get debug logfile ?

**Comment by cmeng-git** [comment]
From main menu
Help | Report bugs
Select an email client to send.

**Comment by narcisgarcia** [comment]
I don't use e-mail on that device. Is there a way to pick a log file?

**Comment by cmeng-git** [comment]
The debug log can be found in aTalk/atakk-logs after you click report bugs. You need to perform the test again before sending the log.

**Comment by cmeng-git** [comment]
The debug log you sent contains little info. It seems that android will clean up the debug info each time you  relaunch aTalk. So you must redo the test to capture the debug info before sending.

Actually the debug info should be retrieved from the device that is sending the invitation, so I can understand whether the invitation is actually being sent.

**Comment by cmeng-git** [comment]
Please provide me with more info or debug log for further investigation. Otherwise I will assume the problem has been resolved or is due to server configuration setup; and requires no action from aTalk.

Kindly note that a joined room must have the following room property enabled, otherwise no sending of invitation is allowed. The room property can only be changed by the owner.
"muc#roomconfig_allowinvites"

**Comment by narcisgarcia** [comment]
I meant someone uses another XMPP client and perfoms the "invite" action. aTalk user is not receiving or notifying that invitation to be accepted.

For example:
Fellow1 with Gajim does "invite my 'Fellow2'"
Fellow2 with aTalk never knows about that invitation.

**Comment by cmeng-git** [comment]
Need clarification on the following:
1. Are both the client accounts reside on the same server?
2. What is the device state of the Fellow2 i.e. is the device in standby (LCD screen in black) or with aTalk in focus showing the contact list screen etc?
3. Can Fellow1 invites other non-aTalk client with the received device in the same test condition?

I really need more details on your setup as I am unable to produce the problem over my side.

**Comment by narcisgarcia** [comment]
1. No: Users are of different servers/domains.
2. Issue has been tested with both users in "Available" status and near enough to watch screens each other. aTalk user in contacts list screen.
3. Not tested that aTalk user performs an invitation to others.

**Comment by cmeng-git** [comment]
Is there any way I can get a test account of the client server that sends the invitation?
I would like to take a look at what is actually being send from the client.

**Comment by cmeng-git** [comment]
With the registered account on the domain1.net, the same server used in your test. I have all the below 4 accounts setup using aTalk clients for testing.
a. parrot@domain1.net
b. swordfish@atalk.sytes.net
c. leopard@atalk.sytes.net
d. swan@atalk.org (not FQDN)

I created a non-persistent room e.g. room-k88z@conference.domain1.net via user parrot.
1. Invitation sent from a.parrot to b.swordfish: swordfish received the invitation and join the room-k88z without any problem.
2. Invitation sent from b.swordfish to c.leopard: leopard received the invitation and join the room-k88z without any problem. 
3. Invitation sent from a.parrot or b.swordfish to d.swan: swan does not receive the invitation. The reason is swan service domain is not a FQDN and hence unreachable by the domain1.net server. This is a normal behavior i.e. all user server must be FQDN in order to set up group chat across domains.

================
If all participants have left the room-k88z, neither b.swordfish or c.leopard can start the group chat, as both the users are not the owners of the room-k88z. Only a.parrot can re-create and start the group chat using room-k88z.

All the above observations are correct, and aTalk invitation feature is working as expected. I am still unable to reproduce the problem experienced by you. I am not sure if the problem is due to non-aTalk client being used, or some room properties specified in your case prevent one from sending the chat invitation, especially if the invitation sender is not the owner of the room.  Please refer to below link for more information on invitation.

[5.1.1 Privileges](https://xmpp.org/extensions/xep-0045.html#roles-priv)

**Comment by narcisgarcia** [comment]
Thank you for your investigation. I'll check further this role circumstances and compare with some other server to host room. Hope I can report solid feedback.

**Comment by cmeng-git** [comment]
Kindly update your latest status.
