### ISSUE TITLE
No chatrooms!

### ISSUE THREAD

**Issue by Reue** [cmeng-git/atalk-android#127]
We have aTalk 2.2.1 (F-Droid "version") installed on the following devices:

On an Huawei Android 7.0 when you slide the screen to the left (that is, begining on the Contacts Page/Tab) you see "Jaber:[username of your XMPP acount]", and bellow that tab you see a list of chatrooms. And you can join anyone of the chatrooms.

On a Samsung S8+ with Android 8.0, when you slide the screen to the left (that is, begining on the Contacts Page/Tab), you only see a blank page, without any menu and without any chatrooms!
And when you click on the "Join Chatroom" icon, a different list of chatrooms appears (different than the one you see on the Huawei Android 7), you can't join any chatroom, and you always see this error message: "Failed to create chat room for: Jabber:[your_username]".

On a Zenfone Max M2 with Android 9.0, it's the as with the Samsung, that is: when you slide the screen to the left (that is, begining on the Contacts Page/Tab), you only see a blank page, without any menu and without any chatrooms!
And when you click on the "Join Chatroom" icon, a different list of chatrooms appears (different than the one you see on the Huawei Android 7), you can't join any chatroom, and you always see this error message: "Failed to create chat room for: Jabber:[your_username]".

So there's serious bugs on the chatrooms feature.

**Comment by cmeng-git** [comment]
The chatroom list page i.e. slide left on contact list. This page lists all the chat rooms that user has joined at one time or another. If you did not join/create any room before, this page will show blank.

When you click join chat room icon on the action bar. the chat room drop-down lists both the ones in the above, and also include all the rooms on the user login server.

Currently there is a bug in v2.2.1 release (accidentally got introduced since v2.2.0); the problem does not exist prior to v2.2.0. Pending on the room to join/create, you may see problem when using the join icon (as in your previous comment). Please see: https://github.com/cmeng-git/atalk-android/issues/120. This will be fixed in the next release.

**Comment by Reue** [comment]
No. Unfortunately that's not the case. Even after joining several chat rooms and creating several other (for instance on Movim), the page you get when, on aTalk app, you slide left on contact list, doesn't show any chat rooms; it's a completely blank page. I have tested this on a couple of Android smartphones and with 3 different accounts!
And when you try to join a chat room, clicking on the join icon, it always fails, with the following error message: "Faile to create chat room for [Jabber:"username_of_your_account"].

**Comment by cmeng-git** [comment]
Need the following info from you:
1. Is the user a registered user on Movim.
2. How do you create/join a chatRoom on Movim

Is there a way I can perform the similar test as you on my side; and what are the steps involved.

**Comment by cmeng-git** [comment]
Please provide status update on your latest finding.
