### ISSUE TITLE
Mobile data retry server ban

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#131]
There was an error whilst using the app on phone data as opposed to wifi. Possibly (unclear) due to aTalk having issues with poor connectivity disconnects.

`XMPPError: policy-violation - modify [policy-violation You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions <stream:error><policy-violation xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='en'>Too many (5) failed authentications from this IP address (XXX.XXX,XXX.XXX). The address will be unblocked at YY:YY:YY ZZ.ZZ.ZZZZ UTC</text></stream:error>]`

After the time aTalk could reconnect but it's unclear if it attempted to keep trying the connection throughout and if on another XMPP server this might lead to a more permanent ban.

**Comment by cmeng-git** [comment]
When user is trying to login to the server unsuccessfully many times, due to an incorrect password or incorrect user account; after a number of attempts within a given time interval (defined by server), the server will treat the attempted logins as hacking attempts, and locked out the user coming in from the specific IP address where the device is connected to. The server will then block further attempts from the device until the blocking time is over as specified in the error message.

You can login again by reconnect your device via another network with different IP or wait until the server blocking time is over. This is server policy-violation protection against hacking and defined by the service provider.

You can read more about communication reliability implementation on aTalk on online hlep:
XEP-0198:Stream Management and ReConnection Manager.

The problem you observed is not attributed to aTalk, any number of **'successfully'** attempts in login to the server, on network disconnection due to fading shall not cause the server to block the device.

**Comment by Aq32** [comment]
Hmm I see. I don't think there should be incorrect logins though since the username and password is autofilled when I've seen the client be disconnected but since this issue has only come up once I don't think I can report more about it for now.

**Comment by cmeng-git** [comment]
The server will lock you out only if you attempt to login with incorrect user name or password. The server will never issue the policy-violation no matter how many times you re-login (successfully) due to network disconnection.
