### ISSUE TITLE
incoming (audio or video) calls are not appeared if the mobile is in steady state (black locked screen) 

### ISSUE THREAD

**Issue by ashfik2000** [cmeng-git/atalk-android#150]
Hi there,

I tested aTalk on many mobiles with different android versions (8.0,8.1 and 10) but i got the same result that incoming (audio or video) calls are not appeared if the mobile is in steady state (black locked screen) until the power button is pressed (the screen is forced to be on).
I know you tried to manage this inside source code (like: ReceivedCallActivity.java) but the screen is still off in case of incoming calls.

public void onAttachedToWindow()
{
   getWindow().addFlags(
            WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON
                    | WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED
                    | WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON
                    | WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD);

}

Best Regards.

**Comment by cmeng-git** [comment]
This is due to another great invention by android:

As of Android version 10 (SDK version 29), the other answers will no longer work if the app is running this in the background, for example in a BroadcastReceiver.

In order to make it work on Android 10 and onwards, you should use a full-screen intent if you really need to start an activity from the background [source]:

Android 10 (API level 29) and higher place restrictions on when apps can start activities when the app is running in the background. These restrictions help minimize interruptions for the user and keep the user more in control of what's shown on their screen.

In nearly all cases, apps that are in the background should display time-sensitive notifications to provide urgent information to the user instead of directly starting an activity. Examples of when to use such notifications include handling an incoming phone call or an active alarm clock.

**Comment by ashfik2000** [comment]
You are right in case of Android 10 and above, but the case exists with android versions (8.0,8.1) and i tried to use PowerManager.WackLock and acquire() function inside onCreate() of ReceivedCallActivity.java to force Turn Screen On but the problem is not solved [ incoming (audio or video) calls are not appeared if the mobile is in steady state]

**Comment by cmeng-git** [comment]
The problem will be resolved in the next aTalk release.

**Comment by cmeng-git** [comment]
Just release v2.3.0. Please verify.

**Comment by ashfik2000** [comment]
I tested  release v2.3.0 on android 8.1 and i realized the following:
1- my above problem still exists [ incoming (audio or video) calls are not appeared if the mobile is in steady state] even with the new version the time-sensitive notification (with  full-screen intent ) is not removing the black screen and turn screen on and pop up the time sensitive notification .

2- in normal situation while using aTalk and receiving incoming call, the notification is ringing but it is  hidden in the task bar (not pop up full-screen intent)  and need to go to task bar and open the notification manually (by the way the old incoming incoming call fragment was looking better :)) )

**Comment by cmeng-git** [comment]
Go to android notification for aTalk, ensure you have the following settings for the 'Call Notification':

![image](https://user-images.githubusercontent.com/7959606/85004514-3a4dc580-b18a-11ea-82e6-257dc5d52687.png)

**Comment by cmeng-git** [comment]
Please see also:
[aTalk UI design & Implementation](https://cmeng-git.github.io/faq.html#ui_01)
