### ISSUE TITLE
Sending files inside MUC group chat failed

### ISSUE THREAD

**Issue by ashfik2000** [cmeng-git/atalk-android#154]
1- inside group chat no problem with test chatting but when trying to send files it gives this error:
Failed to send the selected file.
java.security.cert.CertPathValidationException: Trust anchor for certification path not found.
Hint: this issue may be because i am using openfire 4.5.2 with self-signed certificate but what can i do for this case (without 
         signing the server certificate from CA, if this is the reason)

2- inside 1-1 chat: mobile clients with android 8.1 and above sending/receiving file is done without problems, but for android 8.0
it receives files without problems and in case of sending files the receiving mobile (with higher android versions) shows this error:                               
An error occurred while transferring file from Sender_JID@MyOpenfireServerName
No response received within reply timeout.
Timeout was 5000ms (~5s).While waiting for stream initiation [XMPPTCPConnection[receiver_JID@MyOpenfireServerName/aTalk(0)]

additionally, if the receiver mobile with android version 10, the sender mobile (with android 8) gets a return error message that
receiver_JID@MyOpenfireServerName has rejected this file.

**Comment by cmeng-git** [comment]
1. As like what you have mentioned, the problem is likely to be android trust manager rejected your server self signed certificate during ssl connection. There is little an app like aTalk can do. It is android OS throwing the error. You can get a free certification from [Let's Encrypt](https://letsencrypt.org/).

2. Need more info: 
a. Are you doing plain file transfer or omemo media sharing between devices.
b. Are all devices uses aTalk or others, need to specify.
c. Which device is showing the error message, sender or receiver? both aTalk clients?
d. Are both devices registered on the same server or cross servers?
e. Are both devices connect via Wifi and behind a firewall?
The error indicates that the transfer protocol failed in the mid of negotiation. The sender failed to response to the second part the file stream initiation negotiation. 
Need the debug log from both clients to better understand the problem.

> additionally, if the receiver mobile with android version 10, the sender mobile (with android 8) gets a return error message that
receiver_JID@MyOpenfireServerName has rejected this file.

I need the debug log for both the devices to understand the problem. Please refer to aTalk online help to find out how to send debug log.
