### ISSUE TITLE
Can't move to new contact list.

### ISSUE THREAD

**Issue by Folaht** [cmeng-git/atalk-android#163]
I'm using a Sony XA2 Plus phone with Sailfish X installed.

Error I get:

Attempt to invoke virtual method 'org.jxmpp.jid.BareJid org.jivesoftware.smack.roster.RosterEntry.getJid()' on a null object reference.

**Comment by cmeng-git** [comment]
Please send me the debug log. There are too many possibilities that due to the above problem.
I am unable to guess what is your test setup and contact state before attempt to move.

I did a quick check on my side, I have no problem of moving contact from one group to new group;
except that when the move to group is newly created, the contact list will only get update when user reenter contact list screen.

Also please note, the move contact must be on the your registered server roster, before you attempt to move.
The error message seems to suggest that the move contact is not listed in server roster.

**Comment by cmeng-git** [comment]
aTalk v2.4.0 release has made major changes in the way contact "Move to group" is handled.
Please check and verify if you still see the problem.

**Comment by cmeng-git** [comment]
closed assuming issues resolved with no further update from user.
