### ISSUE TITLE
Advanced settings semi-freezes the application in Sailfish X (8.1)

### ISSUE THREAD

**Issue by Folaht** [cmeng-git/atalk-android#165]
- Sony Xperia XA2, 
 - Sailfish OS (Android 8.1)
- version 2.3.4

When I choose:
- "Settings -> Advanced Settings"
- "Account Settings -> Connection Settings"

my phone semi-freezes and all I can do is enter back, turn off the application and start over again.

**Comment by cmeng-git** [comment]
Please repeat the test and send me the debug log. See online help on how to send debug.

**Comment by Folaht** [comment]
'Main menu -> About -> Report Bugs' sends an e-mail but not a debug log as far as I can tell.
And I can't find 'Help' on the Main Menu.

**Comment by cmeng-git** [comment]
I received a aTalk bug report email without the debug log. But I am not sure if the mail is from you (different sender name).

May be you can provide more info on the problem you have encountered. Please help to provide the following info:
a. Did you means you just access to "Connection Settings"? aTalk does not have "Settings -> Advanced Settings"
"Settings -> Advanced Settings"
"Account Settings -> Connection Settings"

b. Did aTalk successfully log onto your server before you access to the  "Connection Settings"?

c. What are your trying to change in "Connection Settings"

d. Were there any menu item being displayed, when you hit "BackKey" to exit.
  
e. Just in case, ensure the "BOSH-Proxy Configuration" is set to Type: 'NONE' 

f. Were you be able to access to other "Account Settings" e.g. 'Call Encryption settings'

g. Did you manage to send messages to your buddy?

**Comment by Folaht** [comment]
a. Did you means you just access to "Connection Settings"?

I meant both "Connection Settings" in "Account Settings"
as well as "Advanced Settings" in "Settings"

b. yes

c. I just wanted to see what was in there. I was looking for the permission settings which I found.

d. No

e. It is.

f. Yes

g. Yes, but that's outside this issue.

**Comment by cmeng-git** [comment]
The reason for Question g is, I need to know what is aTalk client network status before you select 'Connection Settings'
Sometimes aTalk freezes, while waiting for network response. Seems it is not the case in your setup.

Did you have any settings defined for your 'Client TLS certificates'. Try again after removed them if any.

I have reviewed through the source, if the above still does not solve the problem, I need the actual debug log to really find the root cause.

Please relaunch aTalk and repeat the test, then send me the debug log.

**Comment by cmeng-git** [comment]
issues closed with no further update from user
