### ISSUE TITLE
Publish at F-Droid

### ISSUE THREAD

**Issue by genofire** [cmeng-git/atalk-android#19]
https://f-droid.org/en/contribute/

https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by mulles** [comment]
This issue is a duplicate, it has already been discussed here: https://github.com/cmeng-git/atalk-android/issues/1

Even though, I would be amazed if @cmeng-git  could figure out a way to support a F-droid build with his limited resources. I don't have enough experience to package it myself, lets see if somebody comes along who can.

**Comment by genofire** [comment]
Okay, sry - die not realize - a own F-Droid repository
