### ISSUE TITLE
Other (custom) DNS server

### ISSUE THREAD

**Issue by zimasanya** [cmeng-git/atalk-android#20]
Hi,
it would not be a bad idea to realize the ability to use a custom DNS address

**Comment by cmeng-git** [comment]
I believe the features that you requested is not a chat client option, but feature supported by android if implemented. Otherwise you have to meddle with your corporate network router.

See more info on: [How to Change DNS Settings on Android Devices (WiFi and Cellular)](https://www.xtremerain.com/change-dns-android/)
