### ISSUE TITLE
Move to private chat when click on jabberID in conference.

### ISSUE THREAD

**Issue by paradisaeidae** [cmeng-git/atalk-android#205]
Hi, aTalk is impressive!
I have not explored all the regions.
My humble request is for a private chat session to open when a jabberID is tapped on in a conference user list.
That is all.
Thankyou!
MarkT

**Comment by cmeng-git** [comment]
Are you referring to start a private chat according to  [7.5 Sending a Private Message](https://xmpp.org/extensions/xep-0045.html#privatemessage) or just start a new IM chat session with the selected buddy in the chatRoom.

If you are referring to the [7.5 Sending a Private Message],  did you know of any good xmpp client that implements this. Look like this feature is not popular in all the XMPP clients I have come across. Also unable to find this feature full implementation in the Smack library that is currently used by aTalk.

**Comment by paradisaeidae** [comment]
Hi,
My interest is in the simpler.
Just starting a new IM chat session.

Thanks again!
MarkT

**Comment by cmeng-git** [comment]
Just release aTalk v3.2.0 with the requested features:

![atalk_muc_buddy_context](https://github.com/cmeng-git/atalk-android/assets/7959606/54b5a74c-0e07-4f6f-81f0-011265616c16)

Participant Context Menu:
During a group chat session, long click on a participant avatar will bring up a context menu for user to take action; the available options are pending user role in the group chat:
Start conversation: Start a chat session for the non-anoymous participant; otherwise launch the contact list UI for user selection to start a chat session. This option is availble to all members in group chat.
Grant/Revoke owner privileges: Allow an owner to grant the participant with the moderator privileges.
Remove from group chat: Allow a moderator to remove a buddy from participanting in the current group chat.
A short click on the avatar will copy/remove the buddy nick name in the message send entry box.
aTalk supports receive and display of an incoming Private Messaging; it auto starts a chat session upon received the message.

**Comment by paradisaeidae** [comment]
Impressive!
One of my favorite apps!
Amazed!
MarkT
![Coogee-26](https://github.com/cmeng-git/atalk-android/assets/440482/6865cf92-bc5a-40be-9544-5a1eb90fbac7)
