### ISSUE TITLE
Website, domain and xmpp server?

### ISSUE THREAD

**Issue by poVoq** [cmeng-git/atalk-android#43]
I am wondering about the project infrastructure... there seems to be some confusion over the status of the atalk.org domain and also the website hosting. In addition it might be nice to offer a default xmpp server with open registration?

I rent a basic server infrastructure and also run a Ejabberd instance, so if there is a need I can help out hosting some of it for the time being.

Just let us know what your thought are on this matter.

**Comment by cmeng-git** [comment]
Actually I am only an individual doing aTalk development, a personal contribution to the open source community; and has little to do with any company/organization.

The website atalk.sytes.net FQDN is actually from noip dynamic DNS provider FOC. atalk.org is a virtual host that I used it for aTalk app. There is actually no official registration of the Domain name.

I have a tiny server/computer setup at home. It hosts both the atalk.sytes.net website, and provides the xmpp services based on ejabberd. Both atalk.org and atalk.sytes.net xmpp services are resided on this tiny server, mainly for aTalk development and testing; it is not meant for public registration.

With the limited personal resources, I did not plan for any big goal beyond what currently I am doing for aTalk;  only hoping the community can benefit from aTalk app, a little personal contribution from me.

I certainly welcome if anybody has plan to make aTalk a better app, so more community can benefit from it.

**Comment by poVoq** [comment]
Ok that clarifies it. However I don't think the atalk.org domain is actually available, so it might make sense to change the name of the app to something that would work better?

I actually own the domain "outmo.de" (a little word-play on outmode, e.g. to make something obsolete) which I was thinking of developing into a free community xmpp service. Might be nice home for atalk as well? I could take over hosting a Wordpress website similar to jix.im that can be used in combination with the ejabbered server I run already for another open source community.

I am not much of a developer myself, but I would like to help out with this community project as it seems like it could develop into a really cool xmpp messenger.

**Comment by cmeng-git** [comment]
Yes, I see that someone has registered the atalk.org etc, but no using it, possibly waiting for a business opportunity. However I do not see this has much impact on aTalk app development. Use of atalk.org started in 08/28/2016. The domain name registration is due to expire in 4 days unless the owner renew it.
http://whois.domaintools.com/atalk.org.

atalk.org is used as package name (namespace) for android atalk releases. Changing this name immediately discontinue further updates for all current aTalk users. Changing the package name is no a good approach.

As from user point, they see only aTalk app name, the package name atalk.org has little significant to them. One possible alternative is to use atalk.outmo.de as site to promote and host your community xmpp server, with SIP gateway if need to. aTalk supports telephony SIP gateway for xmpp client to landline call. aTalk roadmap includes video conferencing, but no sure how feasible it is on aTalk.

**Comment by poVoq** [comment]
Yes I agree that changing name is not ideal.

Are you planning to try and get the domain in a few days? Most likely it is set to auto renew though.

Otherwise there might be other free atalk.* domains to use?

**Comment by cmeng-git** [comment]
> Are you planning to try and get the domain in a few days?
Actually no, sorry to say that; Registered and DNS support require yearly and long term commitment. Otherwise I would had registered when aTalk was released.

> Otherwise there might be other free atalk.* domains to use?
You can use the link below to find out more:
https://sg.godaddy.com/domainsearch/find?isc=gofhsg46&checkAvail=1&tmskey=1dom_03_godaddynb&domainToCheck=atalk

**Comment by poVoq** [comment]
Ok, I'll see if it becomes available then. I don't mind that much to spend the 18 euros a year if that helps a open source project. But I doubt it will actually become available.
