### ISSUE TITLE
RFE: XEP-0368 SRV records for XMPP over TLS

### ISSUE THREAD

**Issue by git001** [cmeng-git/atalk-android#45]
Please can you add https://xmpp.org/extensions/xep-0368.html to atalk, thanks

**Comment by cmeng-git** [comment]
Current aTalk has already support login with SRV record. Please see the following online help.

[What information to enter in "Override server setting" when I setup a new account?](https://atalk.sytes.net/atalk/faq.html#account_02)

**Comment by git001** [comment]
Thanks.

My SRV line looks like this

```
dig +short _xmpps-client._tcp.DOMAIN SRV
10 1 443 DOMAIN.
```
The shows that you connect direct to 5222 instead to request the SRV record.

https://github.com/cmeng-git/atalk-android/blob/master/aTalk/src/main/java/net/java/sip/communicator/impl/protocol/jabber/ProtocolProviderServiceJabberImpl.java#L901-L910

I have tried to put the DOMAIN 443 into the atalk as described in "Override server setting" but atalk was not able to connect. The same logins with the server works with other clients like gajim and conversations.

https://github.com/cmeng-git/atalk-android/blob/master/aTalk/src/main/java/net/java/sip/communicator/impl/protocol/jabber/ProtocolProviderServiceJabberImpl.java#L885-L900

I looks like that the underlying smack library doesn't search for ` _xmpps-client ` SRV record.

https://github.com/igniterealtime/Smack/blob/master/smack-core/src/main/java/org/jivesoftware/smack/util/DNSUtil.java#L44-L45

I assume when smack have fixed this issue atalk will be able to use it therefore I close this issue

**Comment by cmeng-git** [comment]
There was some error on the aTalk online help. I have corrected the operation description error in the online help.

Would you be able to provide me with a test account on your server, so I can verify the operations.
(send the account info directly to my email account if this is OK with you).
It was quite some time ago that I tested these features. May be there some changes in the new smack library that required aTalk source changes.

**Comment by git001** [comment]
@cmeng-git thank you for your time and effort.

**Comment by cmeng-git** [comment]
I just tested SRV support with the test account provided.
aTalk throws the following error i.e. SRV record lookup failed, and aTalk attempts to use the default port 5222 to login. Hence it also failed:

`2019-07-31 16:58:04.853 2913-4515/org.atalk.android E/(ProtocolProviderServiceJabberImpl.java:1028)#connectAndLogin: Encounter problem during XMPPConnection: The following addresses failed: '_xmpp-client._tcp.me2digital.im:5222' failed because: org.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.me2digital.im.	IN	SRV yielded an error response NX_DOMAIN, 'me2digital.im:5222' failed because: /144.76.24.100 exception: java.net.SocketTimeoutException: failed to connect to /144.76.24.100 (port 5222) from /192.168.1.29 (port 38782) after 30000ms, me2digital.im/2a01:4f8:191:30::2 exception: java.net.ConnectException: failed to connect to me2digital.im/2a01:4f8:191:30::2 (port 5222) from /:: (port 0) after 29999ms: connect failed: ENETUNREACH (Network is unreachable)`

When I traced into MiniDnsResolver#lookupSRVRecords0(), your server returns the following result i.e. status code NX_DOMAIN:
`org.minidns.hla.SrvResolverResult
Question: _xmpp-client._tcp.me2digital.im.	IN	SRV
Response Code: NX_DOMAIN 
`
I also use an online tool to verify, it too produces an error:
[Check DNS SRV records for XMPP](https://kingant.net/check_xmpp_dns/?h=me2digital.im)

It seems there is some error in your server setup for SRV record retrieval.

**Comment by cmeng-git** [comment]
I have also tried with Override server setting, it too failed to login. Running nslookup produces the following result. Are these ip4/ip6 addresses belong to your xmpp server or the server houses the SRV record?

```
$:~/sandbox/cmeng-git/atalk-android$ nslookup me2digital.im
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	me2digital.im
Address: 144.76.24.100
Name:	me2digital.im
Address: 2a01:4f8:191:30::2
```

**Comment by git001** [comment]
I don't want to offer `_xmpp-client._tcp.` only `_xmpps-client._tcp.` never the less. thanks for your time.
