### ISSUE TITLE
Report bugs action should ask for storage permission

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#48]
..if not granted yet, and not just crash
```
E (FileBackend.java:188)#getaTalkStore: Could not create atalk folder: /storage/emulated/0/Download/aTalk/atalk-logs
E (LogsCollector.java:92)#collectLogs: java.io.FileNotFoundException: /storage/emulated/0/Download/aTalk/atalk-logs.zip (No such file or directory)
E (LogsCollector.java:92)#collectLogs:   at org.atalk.android.aTalkApp.showSendLogsDialog(aTalkApp.java:517)
E (LogsCollector.java:92)#collectLogs:   at org.atalk.android.gui.About.onClick(About.java:217)
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.atalk.android, PID: 24635
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference
E AndroidRuntime:        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:723)
E AndroidRuntime:        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
E AndroidRuntime:        at org.atalk.persistance.FileBackend.getUriForFile(FileBackend.java:229)
E AndroidRuntime:        at net.java.sip.communicator.plugin.loggingutils.LogUploadServiceImpl.sendLogs(LogUploadServiceImpl.java:68)
E AndroidRuntime:        at org.atalk.android.aTalkApp.showSendLogsDialog(aTalkApp.java:517)
E AndroidRuntime:        at org.atalk.android.gui.About.onClick(About.java:217)
E AndroidRuntime:        at android.view.View.performClick(View.java:6648)
E AndroidRuntime:        at android.view.View.performClickInternal(View.java:6620)
E AndroidRuntime:        at android.view.View.access$3100(View.java:787)
E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26167)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7539)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E (UtilActivator.java:90)#uncaughtException:     at org.atalk.persistance.FileBackend.getUriForFile(FileBackend.java:229)
E (UtilActivator.java:90)#uncaughtException:     at org.atalk.android.aTalkApp.showSendLogsDialog(aTalkApp.java:517)
E (UtilActivator.java:90)#uncaughtException:     at org.atalk.android.gui.About.onClick(About.java:217)
E (ExceptionHandler.java:79)#uncaughtException:  at org.atalk.persistance.FileBackend.getUriForFile(FileBackend.java:229)
E (ExceptionHandler.java:79)#uncaughtException:  at org.atalk.android.aTalkApp.showSendLogsDialog(aTalkApp.java:517)
E (ExceptionHandler.java:79)#uncaughtException:  at org.atalk.android.gui.About.onClick(About.java:217)

```

**Comment by cmeng-git** [comment]
You must give storage access to aTalk to store data and files.

**Comment by licaon-kter** [comment]
Yes, but the app should cope with the possibility that Storage has not yet been granted, and ask for it when _needed_.

**Comment by cmeng-git** [comment]
Please refer to online help on permission grants. aTalk would not prompt user if user has selected 'don,t ask again'.

**Comment by licaon-kter** [comment]
That's false for two reasons :)

One, the error above happens when I neither grant nor deny the permission, just press DONE in the first screen

Two, I [still see the annoying screen on every start](https://github.com/cmeng-git/atalk-android/issues/9#issuecomment-523929567) albeit I already checked "don't ask again"

**Comment by cmeng-git** [comment]
For aTalk to work properly, the storage permission must be granted at a minimum. aTalk requires storage access to store some vital information for aTalk to work properly. You will see aTalk fails at time unexpectedly if you deny storage permission for aTalk. It is not just for debug report requires this permission.

I have just tested again on all my android Samsung devices (Note 8, J7, S9) that implements run-time permissions request (android-M and above). I am unable to reproduce the problem as reported:
> Two, I [still see the annoying screen on every start](https://github.com/cmeng-git/atalk-android/issues/9#issuecomment-523929567) albeit I already checked "don't ask again"

Below is the comment embedded in aTalk source during implementation and testing; and their meaning:
1. atalk will always prompt for permission grant if none are set to permanently denied on every aTalk new launch. This is to take care of user whom had unintentionally denied the permission on initial use. Normally user should not Exit aTalk as this ends aTalk completely. User should use Back Button to close aTalk instead. Note some apk do even provide Exit button e.g. conversations. May be aTalk should also consider to remove the Exit option.

2. Some android devices has incorrectly implemented the "PERMANENTLY DENIED"; hence aTalk will always prompt user for permission grants due to incorrect return results by OS.

3. aTalk will repeatedly prompts user for actions if less than 3 permissions have been granted even if they are permanently denied. aTalk will likely not to operate properly under these condition. Some apk just terminate and refuse to launch; aTalk has avoid doing this. Currently this is aTalk implementation and it is doing a simple check. I believe this is what you are experienced.

aTalk has many features and required all the permissions to be granted to explore the aTalk potential. If users have concerned to grant permissions to aTalk, I would encourage these users to use Conversations instead; as most of these permissions are not required in this apk to operate.

```
        // Proceed to request user for permissions if not all are permanently denied
        for (PermissionDeniedResponse response : deniedPermissionResponses) {
            if (!response.isPermanentlyDenied())
                return true;
        }
        /*
         * It seems that some android devices have init all requested permissions to permanently denied states
         * i.e. incorrect return value for: ActivityCompat.shouldShowRequestPermissionRationale == false
         * Must prompt user if < 3 permission has been granted to aTalk - will not work in almost cases;
         *
         * Do not disturb user, if he has chosen partially granted the permissions.
         */
```

**Comment by licaon-kter** [comment]
Your answer answers nothing.

When pressing the save log button the app should either:
a) save the log internally (not in my Download folder) and start a Share intent
Or
b) see **if** it has the Storage permission and if it has, save and share, BUT if it DOESN'T then it needs to prompt the user to grant it

**Comment by cmeng-git** [comment]
When aTalk first starts, the permission request prompt does display the following alert message:

`For application maximum performance and full features support, aTalk requires you to grant permissions for the following services. Without them, aTalk may not work or may have unexpected behavior!`

If user chooses to ignore these alert messages, I see little point for aTalk to alert user on every occurrence of problem due to permission restriction.

Since aTalk requires file storage permission even for normal operations, seriously to avoid problem, aTalk should just exit aTalk when user does not want to grant this permission.

aTalk is open source. If one is so concern to grant resource permission to aTalk, I would advice one to avoid using aTalk.

**Comment by licaon-kter** [comment]
> aTalk requires file storage permission even for normal operations,

Where are these stored so I can delete them?

If this is true an app uninstall would leave files on my storage, and these corrupt files could impede the app functionality on reinstall, right?

**Comment by cmeng-git** [comment]
All of them are stored under your Download/aTalk, the location for all your received files.

The rest are in apk specific directory, and should automatically be removed by android OS when you uninstalled aTalk.

**Comment by licaon-kter** [comment]
> All of them are stored under your Download/aTalk, the location for all your received files.

There is nothing there (unless I press send report), you said that "even for normal operations", so for OMEMO?

**Comment by cmeng-git** [comment]
All the avatars and operation vital info are stored in apk specific directory.  Users do not have the permission to view these directories unless your device is rooted. All these content will be removed once you uninstalled aTalk

There will not have anything stored in Download/aTalk if your never received files or send debug log.

**Comment by licaon-kter** [comment]
> There will not have anything stored in Download/aTalk if your never received files or send debug log.

Are we lost in translation again?

So STORAGE is NOT needed UNLESS I receive files or try to send the log, right? Hence all these posts where "all permissions are needed" are rather FUD.

Ok, I get it, coding _"ask for permission as needed"_ is extra work, yes, but don't harass me on every effing start with **"allow these permissions or nothing works"** when I can't even send a normal message let alone try Video, Audio, Audio message, OMEMO encrypted files and any other feature.

**Comment by cmeng-git** [comment]
aTalk application design is assuming user would at one time or another want to use all the features implemented in aTalk.

"ask for permission as needed"  is not just an extra work on apps that were developed before Google suddenly introduces an after thought requirements on Runtime Permission request. As for aTalk, the code was designed without that new requirement in mind. To add "ask for permission as needed" practically has to add at everything source location that makes access to android resources with that restrictions, or made a major change to the code structure which most likely will break the app one way or another.

"ask for permission as needed" may not completely resolve the problem. Imaging the scenario below:
User is attempting to make a video call, a file transfer came in; Then user is immediately bombarded
with three permissions requests i.e. camera, mic and storage. How do you think user will react to all these prompts.

Frankly speaking, Google is the one to be blamed for create all this mess. Currently android OS already have implemented the gatekeeper to check for permissions. Why can't android OS adds the user prompt to request for user approval, and throw an exception or pass the user result back to apk for action.  This will make the apk implementation much easier. All apk need is to init the Resource Access with app name and the reason for it on apk startup.

Alternately, android OS can prompt the user at apk installation time. User must manually check each permission request with yes and no. I do not see any advantage gained whether the request is at installation or at run time.

But sad to say, android created the mess and just throw the mess to the developers to clean up.

As for the problem you have encounter, the root cause has been identified:
[java.lang.IllegalArgumentException: signedPreKeyId MUST be greater than 0.](https://github.com/cmeng-git/atalk-android/issues/47)
