### ISSUE TITLE
Add option to disable MUC user status info

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#50]
...like join, leave, status changes.

**Comment by cmeng-git** [comment]
In all the xmpp clients I have tested so far .e.g. gajim, pidgin and jitsi etc, when an user is in conference session, there is always a side panel showing all the participants in the room in realtime. As aTalk cannot have this extra panel to show the room participants due to screen size, it is therefore necessary to alert user when there is an event update sent from server i.e. a participant joined or left the room etc.

Imaging if you are in chat room, and need to start some important discussion with some VIP invitation to join and contribute. Without the join event being displayed, you will  have to keep checking for the invited VIP presence before start the discussion.

aTalk is designed to suit general public, and cannot change to cater for each individual preference.

**Comment by licaon-kter** [comment]
The general public wants, when opening the app, 256 messages (multiplied by the number or of joined MUCs) with _"User X joined the chat right now"_ even if that's false? (It's false because aTalk says they joined NOW, yet ONLY THE USER is joining now)

In Gajim you can disable these... you didn't find the toggle?

**Comment by susobaco** [comment]
I also think it can be a problem, my contacts, they do not care about the information of who is in the room or when it came in. I think it's a good option to try to include a list of members and leave contact messages alone in the room.

**Comment by cmeng-git** [comment]
Yes, under certain circumstances, you really do not care who are in the chat room e.g. in a community chat session. Me too do not care under this circumstance.

However consider the following scenario:
If you are in group chat with 8 other colleagues discussing on some company important matter. Then the group think the boss needs to join the discussion to provide some guidance on decision making. So you sends the invitation to your boss. Your boss is in an important meeting, so he reverts with reason and reject the invitation. All the people are unaware of the situation as all like you have disable the chat room event. After a while all the other colleagues see that there is no input from the boss. So each of your 8 colleagues take the initiative to send the invitations. I hope you see the reason why room event can be important.

May be it is the way the events are being delivered to the user, and aTalk needs to see how to improve this and not just disable it.

**Comment by cmeng-git** [comment]
Improve room UI in MUC session on participant join and subject change events in aTalk v2.0.5

**Comment by licaon-kter** [comment]
Still no way to disable join/leaves?

**Comment by cmeng-git** [comment]
aTalk v2.0.5 already made the improvement not to show all existing participants already in the room or subject changed prior to user joining the MUC. aTalk will always show participants' status or subject changes after the user has joined the room.

aTalk does not want to implement an option to allow user to hide/disable participant or subject change when the user is in the room.

**Comment by licaon-kter** [comment]
I've said _"join/leaves"_, in a big MUC there's constant spam with "user X joined", "user X left"

**Comment by licaon-kter** [comment]
That being said, I see the messages disappear after a while, not sure what's the flow, there's a timeout?

**Comment by cmeng-git** [comment]
aTalk has implemented an user option to disable/enable the room member presence status change and subject change message notification. It will be in next aTalk release.
