### ISSUE TITLE
Implement in app downloading

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#51]
...and not rely on Android Download manager which leaks user info like: Android version, Android device model.

**Comment by cmeng-git** [comment]
aTalk is an application designed to run on android OS. It is difficult to accept a request, not to use function implemented in android supporting libraries.

You should revert to android OS development to raise your concerns.

**Comment by licaon-kter** [comment]
At least add a warning so users know that, even when OMEMO is used, aTalk will leak to the server their device identification, Android version and whatnot.

**Comment by licaon-kter** [comment]
Also, keep in mind that while Conversations and browsers can upload/download fine, this AndroidManager still fails with TLS errors or something (https://github.com/cmeng-git/atalk-android/issues/54)

**Comment by cmeng-git** [comment]
Under Note-5 (API-21), aTalk failed to upload file due to TLS handshake error. Conversations also failed to upload file to your server.

If problem is found to be due to Android Download Manager, you too can report the problem to android OS team for their action.

> At least add a warning so users know that, even when OMEMO is used, aTalk will leak to the server their device identification, Android version and whatnot.

Kindly refer to the main page License, aTalk is provided as it, and will not provide such statement.
