### ISSUE TITLE
App going offline if not in foreground

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#55]
Mate 9 stock Pie

Notification is ON, was excluded from battery optimizations

Server log says:
```
[info] <0.1064.0>@mod_stream_mgmt:transition_to_pending:451 (tls|<0.1064.0>) Closing c2s connection for user@mydomain.tld/atalk: Connection failed: connection closed; waiting 300 seconds for stream resumption
```

I look at the notification, still says Online, I open the app and there is says Offline.
Look at the notification now,  it says Offline too.

Server logs some info again, aTalk is reconnecting.

4 more minutes pass... I upload a file that aTalk should react to.

Notification says Offline, aTalk reconnects, notification says Online and a new one appears with the file.

**Comment by cmeng-git** [comment]
Please refer to the following for aTalk Auto Resume and Keep Alive Ping:
a. [XEP-0198:Stream Management and ReConnection Manager](https://atalk.sytes.net/atalk/faq.html#feature_06)
b. [Network Keep Alive - Ping Interval Optimization](https://atalk.sytes.net/atalk/faq.html#feature_07)

Please note you must set up aTalk to enable and setup the Ping interval if your server does not have the Ping function enabled. Otherwise most network services will disconnect the device if left idle. 

Current smack closes the socket and disconnect from server if there is some exceptions in stanza exchanges. I am unable to tell your what was the problem the connection was closed by smack as I need to see the actual debug log,

The online notification can only be updated in android app UI thread. When the socket is disconnected abruptly by smack due the errors, smack immediately enters the auto re-connection phase to resume. As all these events happen in background, aTalk cannot update any UI thread status e.g. notification. Otherwise android OS will throws exception and crashes aTalk. Therefore it is possible that the event and indicator may not necessary happen inSync due to android restriction.

**Comment by licaon-kter** [comment]
> Please refer to the following for aTalk Auto Resume and Keep Alive Ping:
a. XEP-0198:Stream Management and ReConnection Manager
b. Network Keep Alive - Ping Interval Optimization

This is my config: https://gist.github.com/licaon-kter/edbc6629722fa1651d47924e15472bf0 so I have what it needs? Do I have to fumble with aTalk settings?

**Comment by cmeng-git** [comment]
Please refer to the ejabberd doc on the mod_ping setup.
[mod-ping](https://docs.ejabberd.im/admin/configuration/#mod-ping)
Per your ejabberd settings, then you need to check that the keep-alive option in aTalk is enabled.

The important thing now is to figure out why aTalk client get disconnected. Ping setup is only one of the possible cause. I need to see the debug log when this happen, in order to ascertain what is the cause of the disconnection problem.

**Comment by licaon-kter** [comment]
Ok, setup `send_pings: true` and now, every ~90 sec it goes offline, after ~90 sec it reconnects, then offline, then online, continously :(

**Comment by licaon-kter** [comment]
Looks like Huawei's aggressive hibernation was at fault (eg: https://dontkillmyapp.com/huawei ), `send_pings` or not, it still got its sockets closed.

Sorry for the noise.

/PS: For the search engines sake, for Huawei Pie ROMs: Android Settings Battery Launch Manager for aTalk toggle automatic management OFF _(in the pop-up keep those 3 settings ON for launch, secondary and foreground!)_ 
This and normal "battery ignore optimizations" seem to be enough on my device. Per the link above I do have that powergenie app enabled but I don't feel I need to disable it, as apps don't missbehave.

**Comment by cmeng-git** [comment]
Thanks for the info. Glad you found the cause.

However I still believe you need to have the keep-Alive option enabled. If your device is connected to server via MOBILE network; some service provider may disconnect device when found there is no network activity for some time. I believe conversations sets this the ping interval to 4 seconds.

You can use aTalk ping optimization to see if this happen. Set the ping interval to some high value and see if this value get re-tune by aTalk ping optimizer.

Note: if you connect via home WiFi, then you may not see the problem.
