### ISSUE TITLE
F-Droid builds has failed

### ISSUE THREAD

**Issue by readyblue** [cmeng-git/atalk-android#61]
hi @cmeng-git 
I was about to check new version to test new features when I have found, that last 2 F-Droid builds has failed. You check it here:

https://f-droid.org/wiki/page/Special:Search/org.atalk.android

You can see there the last 2 version has failed, details here:

https://f-droid.org/wiki/page/org.atalk.android/lastbuild_1106
https://f-droid.org/wiki/page/org.atalk.android/lastbuild_1110

Can you please check what got wrong? Thanks

From report:

> ERROR: Found unknown maven repo 'third_party/m2' at aTalk/build.gradle
WARNING: Found JAR file at aTalk/third_party/m2/org/igniterealtime/smack/smack-jarjared/4.4.0-alpha3-SNAPSHOT/smack-jarjared-4.4.0-alpha3-SNAPSHOT.jar
WARNING: Found JAR file at buildSrc/build/libs/buildSrc.jar
ERROR: Could not build app org.atalk.android: Can't build due to 1 error while scanning

**Comment by cmeng-git** [comment]
Please see below link for more info on third_party/m2 repo existence.

[https://issuetracker.google.com/139821726 Update to gradle-5.4.1 library and build:gradle:3.5.0 on android studio 3.5.0 generated apk has problems.](https://issuetracker.google.com/139821726)

In summary, the third_party/m2 repo contains the single jar built from the smack/maven repository with some sources changes as before. The move to have the new repository is that the android studio/gradle 3.5.0 has problem in handling the previous aTalk build.gradle format.

Previously the generated jars are saved to libs, now it needs to save to third_party/m2 in order to avoid apk generation error with the latest android studio/gradle 3.5.0 release.

**Comment by readyblue** [comment]
Thanks @cmeng-git for update.
Unfortunately I am not Android developer.
Perhaps @IzzySoft and @Rudloff can help resolve this issue

**Comment by IzzySoft** [comment]
I'm no Android dev either, so it won't help pinging me, sorry.

**Comment by Rudloff** [comment]
@cmeng-git What should we change to [our build recipe](https://gitlab.com/fdroid/fdroiddata/blob/cebdf680d4c3089311cb81c89a2bc9beddcb5448/metadata/org.atalk.android.yml#L460)?

**Comment by cmeng-git** [comment]
Base on readyblue commented 10 days ago

> hi @cmeng-git
> I was about to check new version to test new features when I have found, that last 2 F-Droid builds has failed. You check it here:
> 
> https://f-droid.org/wiki/page/Special:Search/org.atalk.android
> 
> You can see there the last 2 version has failed, details here:
> 
> https://f-droid.org/wiki/page/org.atalk.android/lastbuild_1106
> https://f-droid.org/wiki/page/org.atalk.android/lastbuild_1110
> 
> Can you please check what got wrong? Thanks
> 
> From report:
> 
> > ERROR: Found unknown maven repo 'third_party/m2' at aTalk/build.gradle
> > WARNING: Found JAR file at aTalk/third_party/m2/org/igniterealtime/smack/smack-jarjared/4.4.0-alpha3-SNAPSHOT/smack-jarjared-4.4.0-alpha3-SNAPSHOT.jar
> > WARNING: Found JAR file at buildSrc/build/libs/buildSrc.jar
> > ERROR: Could not build app org.atalk.android: Can't build due to 1 error while scanning
 
Actually there is nothing else need to be pre-built. But Fdroid build complaints there is jar found in new directory i.e. third_party/m2 rep. This jar is actually generated/merged by gradle with jars from maven official repository. 

Previously the generated jars are saved to ./libs directory and get included into the built apk. However these jars now have to be saved/merged into single jar in third_party/m2; in order to avoid apk generation error with the latest android studio/gradle 3.5.0 release.

I believe all you need is to do is to make Fdroid to accept the jar in the new  third_party/m2 rep.
You may refer to the below link for more info on third_party/m2 repo existence; a long discussion between android development team and myself on the issue.

https://issuetracker.google.com/139821726 Update to gradle-5.4.1 library and build:gradle:3.5.0 on android studio 3.5.0 generated apk has problems.

**Comment by Rudloff** [comment]
Thanks for the explanation.
I updated the recipe: https://gitlab.com/fdroid/fdroiddata/merge_requests/5769

**Comment by cmeng-git** [comment]
> I updated the recipe: https://gitlab.com/fdroid/fdroiddata/merge_requests/5769

Thanks for the effort to resolve the issue.

**Comment by readyblue** [comment]
@cmeng-git I see the build is successful and new version 2.1.0 is now in the F-Droid repository.
Thanks everyone for help.

**Comment by cmeng-git** [comment]
aTalk v2.1.1 released on 1 Nov 2019, but is not seen in Fdroid repository.
Is there an issue with the build again?

On my AS, I am facing the problem below when built for fdroidDebug, but no sure if this also happen with the fdroid built script:
Android Studio has inconsistent behavior in built for different product implementations; mistakenly strip a needed library for one but not the other
https://issuetracker.google.com/issues/143786637

Please let me know if fdroid built script is also facing the same problem.

**Comment by readyblue** [comment]
hi @cmeng-git , F-Droid builds are fine, just updated to v2.1.1
F-Droid builds are not immediate, it take some time for new version to get there, but that is ok.

**Comment by cmeng-git** [comment]
Actually the problem only happen for BOSH connectivity option; where AS strips off the required library when I built fdroidDebug during testing.  

I just checked fdroid repository on my J7, it still shows v2.1.0, so unable to check if it is working.

**Comment by cmeng-git** [comment]
aTalk v2.1.2 release should fix the BOSH connectivity problem for fdroid built.
