### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by Ri0n** [cmeng-git/atalk-android#63]
1. Нет кнопки "скрыть отключеных" 
2. Не видит мои букмарки на конференции 
3. Контекстное меню на контактах появляется сверху, так что на верхних контактах оно совсем крохотное 
4. Прикол с темой на джойне в мук как-то непонятен. Хотя если создаётся новая конфа то думаю норм 
5. Непонятно как звонить контактам из меню контакта или из диалога. Даже если оно не надискаверилось то лучше бы был перечеркнутый/серый значек звонка где-нибудь 
6. Не поддерживает SIMS xep

sorry for no translation and aggregation in one place. you can create separate issues on your own.

**Comment by cmeng-git** [comment]
1. No "hide disabled" button
Please explain what feature are you refer to. 
Currently there is already a "Hide offline contacts" in the main menu. Not sure if you are referring to this.

2. Doesn't see my bookmakers at the conference
Please see below link on how to use the bookmarks. 
[[20190620] XEP-0048: Bookmarks and autoJoin option for cnference](https://atalk.sytes.net/atalk/faq.html#feature_09)
If this is not what you are referring to, please elaborate what is the exact problem.

3. The context menu on the contacts appears at the top, so on the upper contacts it is very tiny
Please refer to the link below:
[Android Pixel API-26 floating context menu shows only single menu item when clicked view is near the top of the screen](https://issuetracker.google.com/issues/113072045)
The problem is caused by android OS. It has been reported since Aug 23, 2018 12:35PM, but look like android development team does not have the right technical personnel to solve the problem.

4. A joke with a theme on a joy in agony is somehow incomprehensible. Although if a new conf is created, then I think the norms
Cannot quite understand your comment. please explain.

5. It is not clear how to call contacts from the contact menu or from the dialogue. 
In brief, the media call buttons should be visible next to your contact if his/her client supports media call. Please refer to the following help to understand the missing media call buttons.
[ Why the call options button are not shown on some of my contacts in the contact list?](https://atalk.sytes.net/atalk/faq.html#media_01)

Even if it didn’t overcatch, it would be better if the crossed out / gray call icon is somewhere.
This has been extensively discussed in the following thread.
[call button neither displaying nor working most of time #5](https://github.com/cmeng-git/atalk-android/issues/5)

6. Does not support SIMS xep
I suppose you are referring to XEP-0385: Stateless Inline Media Sharing (SIMS)
aTalk features implementation rely heavily on smack library support. aTalk does not add features that are not available or supported by smack; unless the feature is deems important and useful to many people. Currently aTalk has already supported may file transfer protocols; Please refer to the following on aTalk implementation:
[aTalk Fault-Tolerance File Sharing Implementation & Enhancements](https://atalk.sytes.net/atalk/faq.html#feature_05)

**Comment by Ri0n** [comment]
well I guess my atalk version was updated recently.

1) now I see the button to hide disconnected but Russian translation is invalid. It has to be "Скрыть отключенных"

2) for some reason I can't open your link. but in short I made a lot of bookmarks with Psi. And some of them are autojoin, others not. I see aTalk tries to join the ones with autojoin but then I don't see the room in roster or anywhere. Then if I try to click "ChatRoom закладка" (translation looks invalid again) then I don't see any of my bookmarks at all (dropdown list is empty). Then even auto-join bookmarks often fail to join (endless progress) and clicking "back" usually leads to app crash. In other words it's totally unusable. In Conversation for example it works just fine

3) seriously I'd expect to see some workaround. it's just a bad UX as for me.

4) I believe MUC topic better has to be set after join but not in join dialog, but maybe it's a new MUC creation then it's OK.

5) again I can't open the link. something wrong with the certificate. maybe it's my corporate firewall filters suspicious sites. It's better to have a FAQ right here on github wiki pages

6) again link problem. I guess you have to push smack devs :)

**Comment by cmeng-git** [comment]
1. Actually I do not understand Russian. So I rely Google translator to translate "Hide Offline Contact". It would be much appreciated if someone would offer help to translate/correct current Russian translated xml file i.e. ./res/values-ru/string.xml. Your recommendation is to use "Hide disabled", I will change to this in aTalk next release, though not quite understand why 'offline contact' is referred as 'disabled'.

2. From the contact list page, just slide left to get to the chatroom list page.
See [XEP-0048: Bookmarks and autoJoin option for conference](https://cmeng-git.github.io/faq.html#feature_09)
As for the other problems that you have observed, would  you be able to send the debug log for me to take a look. See the online help on how to send debug log.
[How can I give feedback to the developer for any aTalk problem encountered?](https://cmeng-git.github.io/faq.html#general_04)

3. The context menu is completely handle by android OS itself. I had actually reviewed android source, but there is no option for aTalk to set the context dialog mode which may be a possible way to resolve the problem. Actually there are other UI problems that the new android OS has created, aTalk has done whatever way it can to overcome the problem. As for the context menu problem, unless aTalk completely rewrite the whole android OS context menu handler to resolve the issue, which sound impractical for me. As even android team has no solution, I believe the issues cannot be easily resolved. So far I have raised a total of 44 issues on android OS and SDK, only few get resolved. May be one day I need to join android team to help them to solve problem :).

4. Yes, this is the MUC protocol standard; one cannot change the conference subject unless the user has joined the conference. You should be able to change the room subject "Change chatRoom's info" from the conference room pull down menu; and only if have the permission to change it.

5. Actually the online help can also be accessed via the link:
https://github.com/cmeng-git/atalk-android under Documentation section i.e.
[aTalk site](https://cmeng-git.github.io/)

6. Please see and try the aTalk file transfer implementation; and let me know if you still has file sharing problem with your contacts. Unless smack team has the same believe that the requested feature is important, they too would not spent effort to entertain it.

**Comment by vacuumbeef** [comment]
I will help with russian translation, it need some correction.

**Comment by cmeng-git** [comment]
aTalk v2.1.3 has added unread message badges in contact and chatRoom list views, and blocked
history messages send from auto-joined chat rooms. This may have improved some of the problems that your see earlier. Please check it out and let me know the result.
