### ISSUE TITLE
Notifications and vibrate

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#69]
In the Events Notifications settings I'm not able to set some options for certain events. "Vibration" remains greyed out on **every** event. 
For example (not that I've seen/used it) 
- "Call Security On" greys out "Popup notification" 
- "Call Security Error" every option is greyed out
- "Typing Notifications" only "Popup notification" is not greyed out

"Vibration" alert is very useful to me and I would prefer it to sound alerts in many cases. 

I'm also a bit confused by the difference between "Sound on notification device" and "Sound on playback device". 

My phone uses Android 9 and when I press the volume buttons I can set:
- Normal all sounds on
- Phone on vibrate
- Phone muted

Would it be a large rework of the notifications system to be able to set different event notifications for those modes? 

I'd actually be happy to be able to just leave vibrate on as an option so my main issue is "Vibration" not working when my phone is very much capable of it.

**Comment by cmeng-git** [comment]
It is by design, not all notifications are being enabled for each event. The disabled notifications for the event are grayed out; and user is not giving the option to enable it. Actually all these options are inherited from aTalk forked source; and I believe the development team must have spent considerable thought on the ergonomics for the notifications.

We had once designed a phone for a Russian customer, and added vibrator option in the notification. Customer immediately requests to remove vibrator option on all notifications. The have experienced with customers throwing the phones away when the phone vibrates in their hand. Each user thinks differently and it is not possible to cater for each individual preference.

> I'm also a bit confused by the difference between "Sound on notification device" and "Sound on playback device".

Please see help on the options:
[aTalk Notification Events](https://cmeng-git.github.io/faq.html#feature_11)

All user defined notification tones are fully controlled by android ringToneManager; while the default aTalk notifications are set by aTalk. They are handled separately. It is very difficult for aTalk to change android OS ringToneManager behavior nor to apply its behavior to aTalk default notifications.

**Comment by Aq32** [comment]
> We had once designed a phone for a Russian customer, and added vibrator option in the notification. Customer immediately requests to remove vibrator option on all notifications. The have experienced with customers throwing the phones away when the phone vibrates in their hand. Each user thinks differently and it is not possible to cater for each individual preference.

Surely if it's an option (not greyed out) then users can decide for themselves whether to tick/untick the option to use vibrate?

**Comment by cmeng-git** [comment]
As I have mentioned, the event notifications is the ergo design from the forked source. They must have spent time to weight on each option offered to the user.

Further more, I also feel that many users will have difficulties in distinguish which vibrate for which events. Having too many options can sometimes do more harm than good. Therefore  have to decline your request.

**Comment by Aq32** [comment]
Ok thanks for explaining.
