### ISSUE TITLE
Excitement of the microphone when the speaker is turned on.

### ISSUE THREAD

**Issue by oroscobob** [cmeng-git/atalk-android#73]
Excitement of the microphone when the speaker is turned on.
Echoes when talking. 

Opus 48khz excitement microphone almost immediately. 
Opus 8khz excitement of the microphone almost does not occur.
But still the problem is the two-way echo.

**Comment by cmeng-git** [comment]
If you are testing with two phones, please ensure you do not place the two phones next to each other;  and are acoustic fully isolated. Pending on the phone design, sometime placing the phone on table can also cause problem due to local loop back between speaker and mic.

The echo may also be contributed from the remote side through acoustic pick up if the two phones are not fully isolated. You may mute the mic on remote device to see if this is the case as a simple test.

In aTalk voice call implementation, the echo cancellation is fully carried out by android device itself. aTalk does not have echo cancellation implementation. It its likely that the echo cancellation algorithm implementation on android is optimized  for GSM voice call. GSM voice is sampling at 8KHz.

Reducing OPUS sampling to 8KHz, effectively placing a LPF in its audio path; attenuated all high audio frequencies components. This is the reason for the change in performance.

I would not recommend user to tweak any parameter in the advance settings, unless he/she fully understand the implication and effect of the parameter change.

**Comment by oroscobob** [comment]
Samsung A50 (android 9) - Excitement of the microphone when the speaker is turned on.
RR 5.8.5 - Excitement of the microphone when the speaker is turned on.
AOSP - Excitement of the microphone when the speaker is turned on.

Samsung A50: only echo cancelation active checkbox
RR 5.8.5: no checkboxes are active
AOSP: all three checkboxes are active and all three are on

Echo occurs with any combination of these phones. 
The echo is turned off for the other side when the headphones are connected.
If the headphones are connected on both sides, then there is no echo.

The microphone is excited when you turn on the speakers in a conversation, and video conversation.

**Comment by oroscobob** [comment]
Yes, 8kHz, opus. 
8 kHz: the microphone is almost not excited, but there is an echo

**Comment by oroscobob** [comment]
Phones isolated enough for 2000 km

**Comment by cmeng-git** [comment]
As I have explained earlier, the echo cancellations are handled by android OS itself. There is little aTalk can do if this happen. You just has to try alternatives to minimize this problem.

**Comment by oroscobob** [comment]
Yes, “Signal” echo cancellation works.
Yes, “Telegramm” echo cancellation works.
Yes, “WhatsApp” echo cancellation works.

Atalk echo cancellation does not work.

**Comment by oroscobob** [comment]
Video call, turn on the speaker and get a microphone excitement. 
Not everyone has headphones with them.

**Comment by cmeng-git** [comment]
Please try out v2.1.5 and feedback

**Comment by oroscobob** [comment]
Sorry did not see your message. I follow all the changes in your application. Yes, echo cancellation is working now.

**Comment by cmeng-git** [comment]
Thank for the confirmation.
