### ISSUE TITLE
[Feature request] Configurable option to keep Available status all time

### ISSUE THREAD

**Issue by narcisgarcia** [cmeng-git/atalk-android#85]
This feature request tries to solve the online receiving of messages while phone screen is locked (sleep). aTalk seems to switch account status when user puts phone in pocket, and other contacts see this as offline.

**Comment by cmeng-git** [comment]
All these features are already in the aTalk app. Please refer to the online help on the following topics:
[FAQ](https://cmeng-git.github.io/faq.html)

[20180710] XEP-0198:Stream Management and ReConnection Manager
[20181015] Network Keep Alive - Ping Interval Optimization

You must also not to put aTalk under android battery optimization. Otherwise android OS will put aTalk to sleep (offline) when the device is in standby mode. aTalk prompts user for confirmation on this during aTalk startup.

Also if you are using Huawei phone please google online to find more info on battery optimization:
[Stop your Huawei smartphone from closing apps when you lock the screen](https://www.digitalcitizen.life/stop-huawei-from-closing-apps-when-you-lock-screen)

**Comment by ToEatFreshBabies** [comment]
> You must also not to put aTalk under android battery optimization

Can app detect this or prompt user to make these changes on/after installation?

**Comment by cmeng-git** [comment]
The feature has already implemented in aTalk. Please refer to the online help
[Android Battery Optimization & Runtime Permissions Request](https://atalk.sytes.net/atalk/faq.html#feature_08)
